title: Rafael A. Calvo's Personal Website
description: Personal web page for Professor Rafael A. Calvo, showcasing biography, research, publications, and contact information.
baseurl: ""
url: "https://rcalvoic.github.io"
theme: minima
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
exclude:
  - README.md
  - index.md
  - _config.yml